# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15p7BEMXRcpzGydaPZwy-jbJ74hysaSGc
"""

pip install streamlit

import streamlit as st

# TU APP CHILENA - ¡YA FUNCIONA!
st.title("🌾 AgroDash Chile por PredictaCore - Algarrobo")
st.markdown("---")  # Línea separadora

# SLIDER DE HUMEDAD (¡MÚEVELO!)
humedad = st.slider("💧 Humedad del suelo (%)", 0, 100, 50, help="Mueve para ver predicción")

# TU "IA" SIMPLE (MATEMÁTICAS BÁSICAS)
cosecha_predicha = humedad * 2.5  # kg de choclo por hectárea
riesgo_sequia = 100 - humedad

# RESULTADO CON COLORES CHILE
col1, col2 = st.columns(2)

with col1:
    st.metric("🌽 Choclo predicho", f"{cosecha_predicha:.0f} kg/ha")

with col2:
    st.metric("⚠️ Riesgo sequía", f"{riesgo_sequia}%")

# ALERTAS AUTOMÁTICAS
if humedad > 70:
    st.success("✅ **ÓPTIMO** - Riega normal esta semana")
    st.balloons()
elif humedad > 50:
    st.warning("⚠️ **ATENCIÓN** - Monitorea diariamente")
else:
    st.error("🚨 **URGENTE** - Riega INMEDIATAMENTE")

# TU DISEÑO INDUSTRIAL
st.markdown("---")
st.subheader("👨‍💼 Sobre PredictaCore")
st.write("Innovación agrotech desde Algarrobo. Prototipos y soluciones para campos chilenos.")
st.caption("📞 +56 9 84228358 | 📧 contacto@predictacore.com")

# BOTÓN PAGO (¡DINERO!)
st.markdown("---")
if st.button("💳 Premium: 8.000 CLP/mes", type="primary"):
    st.success("✅ **¡PAGADO!** Report PDF personalizado → contacto@predictacore.com")
    st.info("📊 Incluye: Predicción viñas + alertas WhatsApp + diseño 3D sensor")

